server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database.platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop

management:
  endpoints:
   enabled-by-default: false
   web:
    exposure:
      include: 'health,prometheus'
  endpoint:
   health:
    enabled: true
    show-details: always
   prometheus:
    enabled: true

cloud:
  aws:
    region:
      static: sa-east-1
    stack:
      auto: false
    credentials:
      access-key: admin
      secret-key: admin
    fila:
      compra_cartao_credito: http://localhost:9324/queue/compra_cartao_credito
      compra_cartao_credito_aprovada: http://localhost:9324/queue/compra_cartao_credito_aprovada

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
